//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sahara.i18n {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sahara.i18n.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add....
        /// </summary>
        internal static string BS_PREF_ADD {
            get {
                return ResourceManager.GetString("BS_PREF_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result View Mode.
        /// </summary>
        internal static string BS_PREF_MODE {
            get {
                return ResourceManager.GetString("BS_PREF_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Path.
        /// </summary>
        internal static string BS_PREF_SYSTEM_PATH {
            get {
                return ResourceManager.GetString("BS_PREF_SYSTEM_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string CM_ABOUT {
            get {
                return ResourceManager.GetString("CM_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string CM_ADD {
            get {
                return ResourceManager.GetString("CM_ADD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CM_CLOSE {
            get {
                return ResourceManager.GetString("CM_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging.
        /// </summary>
        internal static string CM_DEBUG {
            get {
                return ResourceManager.GetString("CM_DEBUG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string CM_DELETE {
            get {
                return ResourceManager.GetString("CM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoding.
        /// </summary>
        internal static string CM_ENCODING {
            get {
                return ResourceManager.GetString("CM_ENCODING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string CM_EXIT {
            get {
                return ResourceManager.GetString("CM_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string CM_EXPORT {
            get {
                return ResourceManager.GetString("CM_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string CM_FILE {
            get {
                return ResourceManager.GetString("CM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string CM_GENERAL {
            get {
                return ResourceManager.GetString("CM_GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string CM_HOME {
            get {
                return ResourceManager.GetString("CM_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string CM_IMPORT {
            get {
                return ResourceManager.GetString("CM_IMPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        internal static string CM_MODE {
            get {
                return ResourceManager.GetString("CM_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string CM_NAME {
            get {
                return ResourceManager.GetString("CM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string CM_OK {
            get {
                return ResourceManager.GetString("CM_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preference.
        /// </summary>
        internal static string CM_PREF {
            get {
                return ResourceManager.GetString("CM_PREF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        internal static string CM_REPORT {
            get {
                return ResourceManager.GetString("CM_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string CM_SAVE {
            get {
                return ResourceManager.GetString("CM_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string CM_SEARCH {
            get {
                return ResourceManager.GetString("CM_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string CM_SETTINGS {
            get {
                return ResourceManager.GetString("CM_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string CM_STOP {
            get {
                return ResourceManager.GetString("CM_STOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        internal static string CM_TEMPLATE {
            get {
                return ResourceManager.GetString("CM_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string CM_VALUE {
            get {
                return ResourceManager.GetString("CM_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variables.
        /// </summary>
        internal static string CM_VARIABLES {
            get {
                return ResourceManager.GetString("CM_VARIABLES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DEV_DESC {
            get {
                return ResourceManager.GetString("DEV_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string DEV_IP_ADDRESS {
            get {
                return ResourceManager.GetString("DEV_IP_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local AE Qualifier.
        /// </summary>
        internal static string DEV_LOCAL_AE_QUALIFIER {
            get {
                return ResourceManager.GetString("DEV_LOCAL_AE_QUALIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local AP ID.
        /// </summary>
        internal static string DEV_LOCAL_AP_ID {
            get {
                return ResourceManager.GetString("DEV_LOCAL_AP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local P Selector.
        /// </summary>
        internal static string DEV_LOCAL_P_SELECTOR {
            get {
                return ResourceManager.GetString("DEV_LOCAL_P_SELECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local S Selector.
        /// </summary>
        internal static string DEV_LOCAL_S_SELECTOR {
            get {
                return ResourceManager.GetString("DEV_LOCAL_S_SELECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local T Selector.
        /// </summary>
        internal static string DEV_LOCAL_T_SELECTOR {
            get {
                return ResourceManager.GetString("DEV_LOCAL_T_SELECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string DEV_NAME {
            get {
                return ResourceManager.GetString("DEV_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote AE Qualifier.
        /// </summary>
        internal static string DEV_REMOTE_AE_QUALIFIER {
            get {
                return ResourceManager.GetString("DEV_REMOTE_AE_QUALIFIER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote AP ID.
        /// </summary>
        internal static string DEV_REMOTE_AP_ID {
            get {
                return ResourceManager.GetString("DEV_REMOTE_AP_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote MAC.
        /// </summary>
        internal static string DEV_REMOTE_MAC {
            get {
                return ResourceManager.GetString("DEV_REMOTE_MAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote P Selector.
        /// </summary>
        internal static string DEV_REMOTE_P_SELECTOR {
            get {
                return ResourceManager.GetString("DEV_REMOTE_P_SELECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote S Selector.
        /// </summary>
        internal static string DEV_REMOTE_S_SELECTOR {
            get {
                return ResourceManager.GetString("DEV_REMOTE_S_SELECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote T Selector.
        /// </summary>
        internal static string DEV_REMOTE_T_SELECTOR {
            get {
                return ResourceManager.GetString("DEV_REMOTE_T_SELECTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        internal static string DEV_VENDOR {
            get {
                return ResourceManager.GetString("DEV_VENDOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Project.
        /// </summary>
        internal static string HM_CLOSE_PROJ {
            get {
                return ResourceManager.GetString("HM_CLOSE_PROJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        internal static string HM_NEW_PROJ {
            get {
                return ResourceManager.GetString("HM_NEW_PROJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project.
        /// </summary>
        internal static string HM_OPEN_PROJ {
            get {
                return ResourceManager.GetString("HM_OPEN_PROJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run All.
        /// </summary>
        internal static string HM_RUN_ALL {
            get {
                return ResourceManager.GetString("HM_RUN_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Selected.
        /// </summary>
        internal static string HM_RUN_SEL {
            get {
                return ResourceManager.GetString("HM_RUN_SEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string RIBBON_PROJECT {
            get {
                return ResourceManager.GetString("RIBBON_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string RIBBON_SETTINGS {
            get {
                return ResourceManager.GetString("RIBBON_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Case.
        /// </summary>
        internal static string RIBBON_TESTCASE {
            get {
                return ResourceManager.GetString("RIBBON_TESTCASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Project Settings.
        /// </summary>
        internal static string TPS {
            get {
                return ResourceManager.GetString("TPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string TPS_CITY {
            get {
                return ResourceManager.GetString("TPS_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        internal static string TPS_COMMENTS {
            get {
                return ResourceManager.GetString("TPS_COMMENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string TPS_COUNTRY {
            get {
                return ResourceManager.GetString("TPS_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string TPS_CUSTOMER {
            get {
                return ResourceManager.GetString("TPS_CUSTOMER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string TPS_DESC {
            get {
                return ResourceManager.GetString("TPS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        internal static string TPS_POSTAL {
            get {
                return ResourceManager.GetString("TPS_POSTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string TPS_STREET {
            get {
                return ResourceManager.GetString("TPS_STREET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street Num.
        /// </summary>
        internal static string TPS_STREET_NUM {
            get {
                return ResourceManager.GetString("TPS_STREET_NUM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Lab.
        /// </summary>
        internal static string TPS_TEST_LAB {
            get {
                return ResourceManager.GetString("TPS_TEST_LAB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Suite.
        /// </summary>
        internal static string TPS_TEST_SUITE {
            get {
                return ResourceManager.GetString("TPS_TEST_SUITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tester.
        /// </summary>
        internal static string TPS_TESTER {
            get {
                return ResourceManager.GetString("TPS_TESTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string TPS_VERSION {
            get {
                return ResourceManager.GetString("TPS_VERSION", resourceCulture);
            }
        }
    }
}
